<?php

namespace MelodyWen\LaravelCustomAuth;

use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Auth;

/**
 * Class CustomAuthServiceProvider 自定用用户认证
 * @package MelodyWen\LaravelCustomAuth
 */
class CustomAuthServiceProvider extends ServiceProvider
{
    /**
     * 注册任意应用认证／授权服务。
     *
     * @return void
     */
    public function boot()
    {
        /**
         * 自定义用户的提供器
         */
        Auth::provider('custom-user-provider', function ($app, array $config) {
            // Return an instance of Illuminate\Contracts\Auth\UserProvider...
            return new CustomUserProvider();
        });


        /**
         * 自定义一个看守器
         */
        Auth::extend('custom-guard', function ($app, $name, array $config) {
            // 返回一个 Illuminate\Contracts\Auth\Guard 实例...
            return new CustomGuard(Auth::createUserProvider($config['provider']), request(), $config);
        });
    }


    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}